server:
  port: 8222

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: 'health,info'

spring:
  cloud:
    gateway:
      routes:
        - id: security-service
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/auth/**
