server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

jwt:
  secret: '${JWT_SECRET:clave_secreta_para_fittracker_de_al_menos_32_caracteres}'
  expiration: 3600

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fit_tracker_db
    username: tu_usuario
    password: tu_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
